# Generated by Django 6.0.6 on 2026-06-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_author_alter_post_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
